<<<<<<< HEAD
DROP TABLE IF EXISTS test.books;

CREATE TABLE test.books (
  ID INT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(100),
  DESCRIPTION VARCHAR(255),
  AUTHOR VARCHAR(100),
  ISBN VARCHAR(20),
  PRINT_YEAR INT,
  READ_ALREADY TINYINT(1),
  PRIMARY KEY (ID));

=======
DROP TABLE IF EXISTS test.users;

CREATE TABLE test.users (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  AGE INT(11) NOT NULL,
  IS_ADMIN TINYINT(1) NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID));
>>>>>>> 75c8485d2675a0e5920f8b01dfefaeadf7a39dfd
