DROP TABLE IF EXISTS test.users;

CREATE TABLE test.users (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  AGE INT(11) NOT NULL,
  IS_ADMIN TINYINT(1) NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID));